name: Build PROS Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Install ARM Toolchain
        uses: fiam/arm-none-eabi-gcc@v1
        with:
          release: '9-2019-q4'
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: PIP Installer
        uses: BSFishy/pip-action@v1
        with:
          packages: https://github.com/purduesigbots/pros-cli/releases/download/3.1.4/pros_cli_v5-3.1.4-py3-none-any.whl
      - name: Testing PROS Install 
        run: prosv5 --version
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Build PROS Project  
        run: prosv5 make clean all
